In [6]:
import numpy as np

# Criando um Array

In [7]:
j = np.array([[1,2,3,4,5,6], [3,4,5,6,7,8]])
print(j)
print(type(j))

[[1 2 3 4 5 6]
 [3 4 5 6 7 8]]
<class 'numpy.ndarray'>


# np.zeros()

In [9]:
zero_array = np.zeros(shape=(5,3,6))
print(zero_array)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


# np.ones()

In [10]:
um_array = np.ones((2,3))
print(um_array)

[[1. 1. 1.]
 [1. 1. 1.]]


# np.empty()

In [13]:
vazio = np.empty((3,4))
print(vazio)

[[4.74653174e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


# np.arange()

In [14]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


## Informações do array (shape, size, ndim)


In [ ]:
print(array_zeros.shape)
print(array_zeros.size)
print(array_zeros.ndim)


## Criando sequência de números com np.arange


In [21]:
seq1 = np.arange(10)
print(seq1)

seq2 = np.arange(3, 15, 2)
print(seq2)


[0 1 2 3 4 5 6 7 8 9]
[ 3  5  7  9 11 13]


## Criando sequência linear com np.linspace


In [22]:
linear, passo = np.linspace(0, 100, num=20, endpoint=False, retstep=True)
print(linear)
print(passo)


[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60. 65. 70. 75. 80. 85.
 90. 95.]
5.0


## Exercício 1



In [29]:
#Crie um array com 10 zeros usando np.zeros


ex1 = np.zeros(10)
print(ex1)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
## Exercício 2 Crie um array 2D com 4 linhas e 2 colunas preenchido com 1

ex2 = np.ones((4, 2))
print(ex2)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [31]:
## Exercício 3 Crie um array de 5 até 50, pulando de 5 em 5
ex3 = np.arange(5, 51, 5)
print(ex3)


[ 5 10 15 20 25 30 35 40 45 50]


In [32]:
#Exercício 4 — 8 números igualmente espaçados entre 0 e 1

ex4 = np.linspace(0, 1, num=8)
print(ex4)


[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


In [33]:
#Exercício 5 — Shape, size, ndim e média

a = np.array([10, 20, 30, 40, 50])

print("Shape:", a.shape)
print("Size:", a.size)
print("Dimensões:", a.ndim)
print("Média:", a.mean())


Shape: (5,)
Size: 5
Dimensões: 1
Média: 30.0


In [ ]:
# Exercício 5 — explicação completa
#Código do exercício:
#a = np.array([10, 20, 30, 40, 50])


# Aqui nós criamos um array 1D (vetor) com 5 números inteiros.

# 1️⃣ a.shape
# a.shape


# 👉 O que é?
# Mostra o formato do array.

# 👉 Resultado:

# (5,)


# 👉 Como entender isso?

# O 5 significa que existem 5 elementos

# A vírgula indica que é 1 dimensão

# Se fosse 2D, seria algo como (linhas, colunas)

# 2️⃣ a.size
# a.size


# 👉 O que é?
# Mostra o total de elementos no array.

# 👉 Resultado:

# 5


# 👉 Não importa se é 1D, 2D ou 3D — o size sempre conta quantos valores existem no total.

# 3️⃣ a.ndim
# a.ndim


# 👉 O que é?
# Mostra o número de dimensões do array.

# 👉 Resultado:

# 1


# 👉 Significa:

# 1 → vetor (1D)

# 2 → matriz (2D)

# 3 ou mais → tensor

# 4️⃣ a.mean()
# a.mean()


# 👉 O que é?
# Calcula a média dos valores do array.

# 👉 Como o NumPy calcula:

# (
# 10
# +
# 20
# +
# 30
# +
# 40
# +
# 50
# )
# ÷
# 5
# =
# 30
# (10+20+30+40+50)÷5=30

# 👉 Resultado:

# 30.0


# (É 30.0 porque o NumPy trabalha com float em médias.)